/**************************************************************************//**
 * @file     startup_ARMCM0.S
 * @brief    CMSIS-Core(M) Device Startup File for Cortex-M0 Device
 * @version  V2.2.0
 * @date     26. May 2021
 ******************************************************************************/
/*
 * Copyright (c) 2009-2021 Arm Limited. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

                .syntax  unified
                .arch    armv6-m
                .eabi_attribute Tag_ABI_align_preserved, 1

                #if defined(__ARMCC_VERSION)
                #define __INITIAL_SP     Image$$ARM_LIB_STACK$$ZI$$Limit
                .section RESET, "a"
                #elif defined(__GNUC__)
                #define __INITIAL_SP     __StackTop
                .section .vectors, "a"
                #endif

                .align   2
                .globl   __Vectors
                .globl   __Vectors_End
                .globl   __Vectors_Size
__Vectors:
                .long    __INITIAL_SP          /*     Top of Stack */
                .long    Reset_Handler         /*     Reset Handler */
                .long    NMI_Handler           /* -14 NMI Handler */
                .long    HardFault_Handler     /* -13 Hard Fault Handler */
                .long    0x00730023
                .long    0x04000282
                .long    0x434B5942
                .long    0x3031562D
                .long    0                     /*     Reserved for ble device name */
                .long    0                     /*     Reserved for ble device name */
                .long    0                     /*     Reserved for ble device name */
                .long    SVC_Handler           /*  -5 SVCall Handler */
                .long    0x62391020            /*     Reserved for ble bd_addr */
                .long    0                     /*     Reserved for ble bd_addr and otp config */
                .long    PendSV_Handler        /*  -2 PendSV Handler */
                .long    SysTick_Handler       /*  -1 SysTick Handler */

                /* Interrupts */
                .long    RTC_IRQHandler           /*   0  RTC Interrupt */
                .long    USB_IRQHandler           /*   1  USB Interrupt */
                .long    USB_WK_IRQHandler        /*   2  USB_WK Interrupt */
                .long    RF_IRQHandler            /*   3  RF Interrupt */
                .long    WAKEUP_GPIO0_IRQHandler  /*   4  WAKEUP_GPIO0 Interrupt */
                .long    TIMER0_IRQHandler        /*   5  TIMER0 Interrupt */
                .long    0                        /*   6  VBUS Interrupt */
                .long    WDT_IRQHandler           /*   7  WDT Interrupt */
                .long    0                        /*   8  SF0 Interrupt */
                .long    ENCODER_IRQHandler       /*   9  ENCODER Interrupt */
                .long    0                        /*   10  RF DMA Interrupt */
                .long    AES128_IRQHandler        /*   11  AES Interrupt */
                .long    UART0_IRQHandler         /*   12  UART0 RX Interrupt */
                .long    SENSCAN_IRQHandler       /*   13  SENSCAN Interrupt */
                .long    LEDC_IRQHandler          /*   14  LEDC Interrupt */

__Vectors_End:
                .equ     __Vectors_Size, __Vectors_End - __Vectors
                .size    __Vectors, . - __Vectors


                .thumb
                .section .text
                .align   2

                .thumb_func
                .type    Reset_Handler, %function
                .globl   Reset_Handler
                .fnstart
Reset_Handler:
                bl       SystemContextRestore
                bl       SystemInit
                #if defined(__ARMCC_VERSION)
                bl       __main
                #elif defined(__GNUC__)
                ldr      r4, =__copy_table_start__
                ldr      r5, =__copy_table_end__

.L_loop0:
                cmp      r4, r5
                bge      .L_loop0_done
                ldr      r1, [r4]                /* source address */
                ldr      r2, [r4, #4]            /* destination address */
                ldr      r3, [r4, #8]            /* word count */
                lsls     r3, r3, #2              /* byte count */

.L_loop0_0:
                subs     r3, #4                  /* decrement byte count */
                blt      .L_loop0_0_done
                ldr      r0, [r1, r3]
                str      r0, [r2, r3]
                b        .L_loop0_0

.L_loop0_0_done:
                adds     r4, #12
                b        .L_loop0

.L_loop0_done:

                ldr      r3, =__zero_table_start__
                ldr      r4, =__zero_table_end__

.L_loop2:
                cmp      r3, r4
                bge      .L_loop2_done
                ldr      r1, [r3]                /* destination address */
                ldr      r2, [r3, #4]            /* word count */
                lsls     r2, r2, #2              /* byte count */
                movs     r0, 0

.L_loop2_0:
                subs     r2, #4                  /* decrement byte count */
                blt      .L_loop2_0_done
                str      r0, [r1, r2]
                b        .L_loop2_0
.L_loop2_0_done:

                adds     r3, #8
                b        .L_loop2
.L_loop2_done:

                bl       main
                #endif

                .fnend
                .size    Reset_Handler, . - Reset_Handler

/* The default macro is not used for HardFault_Handler
 * because this results in a poor debug illusion.
 */
                .thumb_func
                .type    HardFault_Handler, %function
                .weak    HardFault_Handler
                .fnstart
HardFault_Handler:
                b        .
                .fnend
                .size    HardFault_Handler, . - HardFault_Handler

                .thumb_func
                .type    Default_Handler, %function
                .weak    Default_Handler
                .fnstart
Default_Handler:
                b        .
                .fnend
                .size    Default_Handler, . - Default_Handler

/* Macro to define default exception/interrupt handlers.
 * Default handler are weak symbols with an endless loop.
 * They can be overwritten by real handlers.
 */
                .macro   Set_Default_Handler  Handler_Name
                .weak    \Handler_Name
                .set     \Handler_Name, Default_Handler
                .endm


/* Default exception/interrupt handler */
                Set_Default_Handler  NMI_Handler
                Set_Default_Handler  SVC_Handler
                Set_Default_Handler  PendSV_Handler
                Set_Default_Handler  SysTick_Handler


                Set_Default_Handler  RTC_IRQHandler
                Set_Default_Handler  USB_IRQHandler
                Set_Default_Handler  RF_IRQHandler
                Set_Default_Handler  WAKEUP_GPIO0_IRQHandler
                Set_Default_Handler  TIMER0_IRQHandler
                Set_Default_Handler  WDT_IRQHandler
                Set_Default_Handler  RF_DMA_IRQHandler
                Set_Default_Handler  AES128_IRQHandler
                Set_Default_Handler  UART0_RX_IRQHandler
                Set_Default_Handler  UART0_TX_IRQHandler
                Set_Default_Handler  LEDC_IRQHandler
                Set_Default_Handler  ENCODER_IRQHandler

                .end
